### ISSUE TITLE
Create a new test to validate the usage and persistency of interface available_tags

### ISSUE THREAD

**Issue by italovalcy** [kytos-ng/kytos-end-to-end-tests#108]
Is the available_tags persistent among Kytos resets?

Is mef_eline following the restriction on an interface available tags?

What happens if there is no available tag?

**Comment by viniarck** [comment]
This is being addressed on PR https://github.com/kytos-ng/kytos-end-to-end-tests/pull/262

@Alopalao it might be worth to also add a controller restart in one of the tests or add a new one, even though we know it'll persist correctly for completeness, but let's also assert that in an e2e test just so this thread can be closed.
