### ISSUE TITLE
Move e2e to kytos-ng org

### ISSUE THREAD

**Issue by viniarck** [kytos-ng/kytos-end-to-end-tests#156]
This is to cover this additional scope:

- Move e2e to kytos-ng org
- Cover linter issue #141

**Comment by italovalcy** [comment]
To move the e2e tests to kytos-ng org, some tasks needed to be done:
- Update Gitlab kytos/kytos-end-to-end-tests CI pipeline to use the new location
- Update Gitlab amlight/kytos-end-to-end-tests (manual tests execution for devs) CI pipeline to use the new location
- Update Gitlab amlight/kytos-docker CI pipeline to use the new location (utilizes the MongoDB script)
- Update Gitlab amlight/kytos-docker-prod CI pipeline to use the new location (utilizes the MongoDB script)

**Comment by italovalcy** [comment]
Update Kaban board 2022 Epics

**Comment by italovalcy** [comment]
> * Cover linter issue [Consider enabling linters and formatters  #141](https://github.com/amlight/kytos-end-to-end-tests/issues/141)

Regarding the cover linter issue, we will postpone this improvement for next release because the e2e repo currently have :( 994 issues found. We will have to dive deeper into this before releasing it
