### ISSUE TITLE
Fix: Refactor the e2e test suite.

### ISSUE THREAD

**Issue by gretelliz** [kytos-ng/kytos-end-to-end-tests#229]
`python3 -m pytest tests/test_e2e_40_sdntrace.py::TestE2ESDNTrace::test_070_run_sdntrace_untagged_vlan` was failing because it was trying to create an evc that already existed, so a check was added to remove the evc and avoid the error.

This is to refactor other test cases or lack of teardown that is impacting on other test cases [like this one here](https://github.com/kytos-ng/kytos-end-to-end-tests/pull/226).

**Comment by viniarck** [comment]
Landed on https://github.com/kytos-ng/kytos-end-to-end-tests/pull/258/files
